name: Docker Action
on:
  push:
    branches: [main]
    paths: [hello-world-docker-action/**]
  workflow_dispatch:
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Run Docker Action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@mitchell'
      - name: Output Time
        run: |
          echo "Time: ${{ steps.hello-action.outputs.time }}"
